/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.waiter.administrator;

import producto.*;
import alertas.principal.AWTUtilities;
import alertas.principal.ErrorAlert;
import contract.administrator.BoxContract;
import contract.login.LoginContract;
import exception.ExceptionPvLite;
import java.awt.Frame;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import login.Login;
import model.User;
import presenter.administrator.BoxPresenter;

/**
 *
 * @author pv_lite_team
 */
public class InitialBox extends javax.swing.JDialog implements BoxContract.View {

    Timer timer = null;
    TimerTask task;
    int i = 32;
    static boolean opcion = true;
    int id;
    private final LoginContract.View view;
    private final User user;
    private final BoxPresenter presenter;

    /**
     * Creates new form ModalProducto
     *
     * @param parent
     * @param modal
     * @param view
     * @param user
     */
    public InitialBox(Frame parent, boolean modal, LoginContract.View view, User user) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setOpaque(this, false);
        Ubicar(0);
        this.view = view;
        this.user = user;
        this.presenter = new BoxPresenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        titulo = new javax.swing.JLabel();
        txtInitialBalance = new app.bolivia.swing.JCTextField();
        btnContinue = new principal.MaterialButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtComment = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alertas/img/fondo.png"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(58, 159, 171));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 54, 50));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText(" DINERO EN CAJA");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 266, -1));

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 386, 50));

        txtInitialBalance.setBackground(new java.awt.Color(255, 255, 255));
        txtInitialBalance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 159, 171), 2, true));
        txtInitialBalance.setForeground(new java.awt.Color(58, 159, 171));
        txtInitialBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInitialBalance.setText("0.00");
        txtInitialBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtInitialBalance.setPhColor(new java.awt.Color(58, 159, 171));
        txtInitialBalance.setPlaceholder("Saldo en caja...");
        txtInitialBalance.setSelectionColor(new java.awt.Color(58, 159, 171));
        txtInitialBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInitialBalanceActionPerformed(evt);
            }
        });
        txtInitialBalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInitialBalanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInitialBalanceKeyTyped(evt);
            }
        });
        panel1.add(txtInitialBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 320, 40));

        btnContinue.setBackground(new java.awt.Color(58, 159, 171));
        btnContinue.setForeground(new java.awt.Color(255, 255, 255));
        btnContinue.setText("CONTINUAR");
        btnContinue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContinue.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        panel1.add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 290, 330, 50));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 159, 171)));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(58, 159, 171));
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("");
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(58, 159, 171), 2, true));
        jTextArea1.setSelectionColor(new java.awt.Color(58, 159, 171));
        jScrollPane1.setViewportView(jTextArea1);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 320, -1));

        txtComment.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtComment.setForeground(new java.awt.Color(58, 159, 171));
        txtComment.setText("Comentario:");
        panel1.add(txtComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 320, 20));

        titulo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo2.setForeground(new java.awt.Color(58, 159, 171));
        titulo2.setText("Saldo inicial:");
        panel1.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 78, 320, 20));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        this.task = new TimerTask() {
            public void run() {
                if (InitialBox.this.i == 0) {
                    InitialBox.this.Cerrar();
                } else {
                    InitialBox.this.Ubicar(InitialBox.this.i);
                    InitialBox.this.i -= 32;
                    InitialBox.this.Trasparencia(InitialBox.this.i / 352.0F);
                }
            }
        };
        this.timer = new Timer();
        this.timer.schedule(this.task, 0L, 2L);
    }//GEN-LAST:event_cerrarActionPerformed

    private void txtInitialBalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInitialBalanceKeyTyped
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtInitialBalanceKeyTyped

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        String initialBalanceText = txtInitialBalance.getText();
        float initialBalance = 0;
        if (!initialBalanceText.equals("")) {
            initialBalance = Float.parseFloat(initialBalanceText);
        }
        presenter.createInitialBalance(this.user.getIdUser(), initialBalance, txtComment.getText());
    }//GEN-LAST:event_btnContinueActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 352) {
                    timer.cancel();
                } else {
                    Ubicar(i);
                    i += 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_formWindowOpened

    private void txtInitialBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInitialBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInitialBalanceActionPerformed

    private void txtInitialBalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInitialBalanceKeyReleased
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String initialBalanceText = txtInitialBalance.getText();
            float initialBalance = 0;
            if (!initialBalanceText.equals("")) {
                initialBalance = Float.parseFloat(initialBalanceText);
            }
            presenter.createInitialBalance(this.user.getIdUser(), initialBalance, txtComment.getText());
        }
    }//GEN-LAST:event_txtInitialBalanceKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static principal.MaterialButton btnContinue;
    private principal.MaterialButton cerrar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.panel.Panel panel1;
    public static javax.swing.JLabel titulo;
    public static javax.swing.JLabel titulo2;
    public static javax.swing.JLabel txtComment;
    public static app.bolivia.swing.JCTextField txtInitialBalance;
    // End of variables declaration//GEN-END:variables

    private void Cerrar() {
        this.dispose();
        timer = null;
        task = null;
    }

    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }

    private void Ubicar(int y) {
        this.setLocation(603, y - 200);
    }

    @Override
    public void onError(ExceptionPvLite exceptionPvLite) {
        ErrorAlert errorAlert = new ErrorAlert(new JFrame(), true);
        errorAlert.titulo.setText("Error");
        errorAlert.msj.setText(exceptionPvLite.getMessage());
        errorAlert.msj1.setText("<html>" + exceptionPvLite.getCauseMessage() + "</html>");
        errorAlert.setVisible(true);
    }

    @Override
    public void onShowAdministratorView() {
        view.onShowAdministratorView(this.user);
    }
}
