/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tabla.EstiloTablaHeader;
import tabla.EstiloTablaRenderer;
import tabla.MyScrollbarUI;
import static ventas.Ventas.conn;

/**
 *
 * @author Alejandro
 */
public final class DetallesTicket extends java.awt.Dialog {

    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form DetallesTicket
     */
    public DetallesTicket(java.awt.Frame parent, boolean modal, int ticket) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        efectosTabla();
        llenarTabla(ticket);
    }

    public void efectosTabla() {
        this.modelo.addColumn("PRODUCTO");
        this.modelo.addColumn("PRECIO");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("SUBTOTAL");

        this.tabla.setModel(this.modelo);
        
        TableColumn columnProduct = tabla.getColumn("PRODUCTO");
        columnProduct.setResizable(false);
        columnProduct.setPreferredWidth(100);
        
        TableColumn columnPrice = tabla.getColumn("PRECIO");
        columnPrice.setResizable(false);
        columnPrice.setPreferredWidth(10);
        
        TableColumn columnQuantity = tabla.getColumn("CANTIDAD");
        columnQuantity.setResizable(false);
        columnQuantity.setPreferredWidth(15);
        
        TableColumn columnSub = tabla.getColumn("SUBTOTAL");
        columnSub.setResizable(false);
        columnSub.setPreferredWidth(15);
        
        this.tabla.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tabla.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        tabla.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0, false), "selectColumnCell");
    }

    public void llenarTabla(int ticket) {
        try {
            String sql = "select DISTINCT(nombre),fecha,ticket.total,mesa,precio,cantidad,ventas.total as importe from ticket INNER JOIN ventas on ventas.idTicket=ticket.idTicket INNER JOIN producto on producto.idproducto=ventas.id_Producto where ticket.idTicket=" + ticket + ";";

            PreparedStatement pst = Ventas.conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            Object[] datos = new Object[4];
            while (rs.next()) {
                datos[0] = rs.getString("nombre");
                datos[1] = Float.valueOf(rs.getFloat("precio"));
                datos[2] = Integer.valueOf(rs.getInt("cantidad"));
                datos[3] = Float.valueOf(rs.getFloat("importe"));
                this.modelo.addRow(datos);
                this.mesa.setText(rs.getString("mesa"));
                this.total.setText("$" + rs.getFloat("total"));
                this.fecha.setText(rs.getString("fecha"));
            }
        } catch (SQLException ex) {
            System.out.println("tabla descripcion " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        mesa1 = new javax.swing.JLabel();
        mesa2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        txtOpcion = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 159, 171), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 363));

        mesas.setBackground(new java.awt.Color(58, 159, 171));
        mesas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesas.setForeground(new java.awt.Color(58, 159, 171));
        mesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesas.setText("TOTAL:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        mesa1.setBackground(new java.awt.Color(58, 159, 171));
        mesa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesa1.setForeground(new java.awt.Color(58, 159, 171));
        mesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa1.setText("FECHA:");

        mesa2.setBackground(new java.awt.Color(58, 159, 171));
        mesa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesa2.setForeground(new java.awt.Color(58, 159, 171));
        mesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa2.setText("MESA:");

        fecha.setBackground(new java.awt.Color(58, 159, 171));
        fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(58, 159, 171));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("$0.00");

        total.setBackground(new java.awt.Color(58, 159, 171));
        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(58, 159, 171));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("$0.00");

        mesa.setBackground(new java.awt.Color(58, 159, 171));
        mesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesa.setForeground(new java.awt.Color(58, 159, 171));
        mesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa.setText("$0.00");

        jPanel2.setBackground(new java.awt.Color(58, 159, 171));
        jPanel2.setPreferredSize(new java.awt.Dimension(535, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 60, 50));

        txtOpcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtOpcion.setForeground(new java.awt.Color(255, 255, 255));
        txtOpcion.setText("DETALLES DEL TICKET");
        jPanel2.add(txtOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(9, 9, 9))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(420, 420, 420))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesTicket dialog = new DetallesTicket(new java.awt.Frame(), true, 4);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel mesa1;
    private javax.swing.JLabel mesa2;
    private javax.swing.JLabel mesas;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel total;
    private javax.swing.JLabel txtOpcion;
    // End of variables declaration//GEN-END:variables
}
