/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tabla.EstiloTablaHeader;
import tabla.EstiloTablaRenderer;
import tabla.MyScrollbarUI;
import static ventas.Ventas.conn;

/**
 *
 * @author Alejandro
 */
public final class DetallesTicket extends java.awt.Dialog {

    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form DetallesTicket
     */
    public DetallesTicket(java.awt.Frame parent, boolean modal, int ticket) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        efectosTabla();
        llenarTabla(ticket);
    }

    public void efectosTabla() {
        this.modelo.addColumn("PRODUCTO");
        this.modelo.addColumn("PRECIO");
        this.modelo.addColumn("CANTIDAD");
        this.modelo.addColumn("SUBTOTAL");

        this.tabla.setModel(this.modelo);

        this.tabla.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tabla.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tabla.setSelectionMode(0);
        this.jScrollPane1.getViewport().setBackground(new Color(255, 255, 255));
        this.jScrollPane1.getViewport().setBackground(new Color(255, 255, 255));
        this.jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        this.jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
    }

    public void llenarTabla(int ticket) {
        try {
            String sql = "select DISTINCT(nombre),fecha,ticket.total,mesa,precio,cantidad,ventas.total as importe from ticket INNER JOIN ventas on ventas.idTicket=ticket.idTicket INNER JOIN producto on producto.idproducto=ventas.id_Producto where ticket.idTicket=" + ticket + ";";

            PreparedStatement pst = Ventas.conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            Object[] datos = new Object[4];
            while (rs.next()) {
                datos[0] = rs.getString("nombre");
                datos[1] = Float.valueOf(rs.getFloat("precio"));
                datos[2] = Integer.valueOf(rs.getInt("cantidad"));
                datos[3] = Float.valueOf(rs.getFloat("importe"));
                this.modelo.addRow(datos);
                this.mesa.setText(rs.getString("mesa"));
                this.total.setText("$" + rs.getFloat("total"));
                this.fecha.setText(rs.getString("fecha"));
            }
        } catch (SQLException ex) {
            System.out.println("tabla descripcion " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        mesa1 = new javax.swing.JLabel();
        mesa2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        materialButton1 = new principal.MaterialButton();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(58, 159, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mesas.setBackground(new java.awt.Color(58, 159, 171));
        mesas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesas.setForeground(new java.awt.Color(255, 255, 255));
        mesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesas.setText("TOTAL:");
        jPanel1.add(mesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 550, 240));

        mesa1.setBackground(new java.awt.Color(58, 159, 171));
        mesa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesa1.setForeground(new java.awt.Color(255, 255, 255));
        mesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa1.setText("FECHA:");
        jPanel1.add(mesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 40));

        mesa2.setBackground(new java.awt.Color(58, 159, 171));
        mesa2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesa2.setForeground(new java.awt.Color(255, 255, 255));
        mesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa2.setText("MESA:");
        jPanel1.add(mesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        fecha.setBackground(new java.awt.Color(58, 159, 171));
        fecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("--");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 40));

        total.setBackground(new java.awt.Color(58, 159, 171));
        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("--");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 200, 40));

        mesa.setBackground(new java.awt.Color(58, 159, 171));
        mesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesa.setForeground(new java.awt.Color(255, 255, 255));
        mesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa.setText("--");
        jPanel1.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 40));

        materialButton1.setForeground(new java.awt.Color(58, 159, 171));
        materialButton1.setText("ACEPTAR");
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(materialButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 230, 40));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_materialButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesTicket dialog = new DetallesTicket(new java.awt.Frame(), true, 4);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private principal.MaterialButton materialButton1;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel mesa1;
    private javax.swing.JLabel mesa2;
    private javax.swing.JLabel mesas;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
