/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tabla.EstiloTablaHeader;
import tabla.EstiloTablaRenderer;
import tabla.MyScrollbarUI;
import static ventas.Ventas.conn;

/**
 *
 * @author Alejandro
 */
public final class DetallesTicket extends java.awt.Dialog {
 DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    /**
     * Creates new form DetallesTicket
     */
    public DetallesTicket(java.awt.Frame parent, boolean modal,int ticket) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        efectosTabla();
        llenarTabla(ticket);
    }
public void efectosTabla(){
   modelo.addColumn("PRODUCTO");
        modelo.addColumn("PRECIO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("SUBTOTAL");
        
        tabla.setModel(modelo);



      tabla.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
       tabla.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        
}
     public void remove(){
       int filas = modelo.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
    }
public void llenarTabla(int ticket){
    remove();
    try {
            String sql = "select DISTINCT(nombre),fecha,ticket.total,"
                    + "mesa,precio,cantidad,ventas.total as importe "
                    + "from ticket INNER JOIN ventas on ventas.idTicket="
                    + "ticket.idTicket INNER JOIN producto on producto.idproducto"
                    + "=ventas.id_Producto where ticket.idTicket="+ticket+";";
//            System.out.println(sql);
  PreparedStatement pst=conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            Object datos[] = new Object[4];
            while (rs.next()) {
                    
                    datos[0]= rs.getString("nombre");
                    datos[1]= rs.getFloat("precio");
                    datos[2]= rs.getInt("cantidad");
                    datos[3]= rs.getFloat("importe");
                   modelo.addRow(datos);
                   mesa.setText(rs.getString("mesa"));
                   total.setText("$"+rs.getFloat("total"));
                   fecha.setText(rs.getString("fecha"));
            } 
            } catch (SQLException ex) {
            System.out.println("tabla descripcion "+ex.getMessage());
        }
}
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mesas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        mesa1 = new javax.swing.JLabel();
        mesa2 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        mesa = new javax.swing.JLabel();
        materialButton1 = new principal.MaterialButton();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(58, 159, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mesas.setBackground(new java.awt.Color(58, 159, 171));
        mesas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesas.setForeground(new java.awt.Color(255, 255, 255));
        mesas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesas.setText("TOTAL:");
        jPanel1.add(mesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 540, 240));

        mesa1.setBackground(new java.awt.Color(58, 159, 171));
        mesa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesa1.setForeground(new java.awt.Color(255, 255, 255));
        mesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa1.setText("FECHA:");
        jPanel1.add(mesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 200, 40));

        mesa2.setBackground(new java.awt.Color(58, 159, 171));
        mesa2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesa2.setForeground(new java.awt.Color(255, 255, 255));
        mesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa2.setText("MESA:");
        jPanel1.add(mesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        fecha.setBackground(new java.awt.Color(58, 159, 171));
        fecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("--");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 200, 40));

        total.setBackground(new java.awt.Color(58, 159, 171));
        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("--");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 200, 40));

        mesa.setBackground(new java.awt.Color(58, 159, 171));
        mesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mesa.setForeground(new java.awt.Color(255, 255, 255));
        mesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesa.setText("--");
        jPanel1.add(mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 200, 40));

        materialButton1.setForeground(new java.awt.Color(0, 204, 153));
        materialButton1.setText("ACEPTAR");
        materialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(materialButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 180, 40));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void materialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButton1ActionPerformed
            dispose();
    }//GEN-LAST:event_materialButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesTicket dialog = new DetallesTicket(new java.awt.Frame(), true,4);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private principal.MaterialButton materialButton1;
    private javax.swing.JLabel mesa;
    private javax.swing.JLabel mesa1;
    private javax.swing.JLabel mesa2;
    private javax.swing.JLabel mesas;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
