/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.administrator;

import alertas.principal.ErrorAlert;
import java.awt.Color;
import contract.administrator.CashCourtContract1;
import exception.ExceptionPvLite;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import model.Court;
import model.Spents;
import presenter.administrator.CashCourtPresenter1;
import principal.PrincipalAdministrador;
import tabla.EstiloTablaHeader;
import tabla.EstiloTablaRenderer;
import tabla.MyScrollbarUI;
import view.administrator.DetailsCashCourt;

/**
 *
 * @author Rojeru San
 */
public class CashCourtView1 extends javax.swing.JInternalFrame implements CashCourtContract1.View {

    private final DefaultTableModel modelo;
    private final DefaultTableModel modeloSpent;
    private final PrincipalAdministrador desktop;
    private final CashCourtPresenter1 presenter;
    public DetailsCashCourt info;

    /**
     * Creates new form NewJInternalFrame
     *
     * @param desktop
     */
    public CashCourtView1(PrincipalAdministrador desktop) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modeloSpent = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        DetailsCashCourt info = null;
        this.info = info;
        tableStyles();
        this.desktop = desktop;
        this.presenter = new CashCourtPresenter1(this);
        this.presenter.onLoadMoneyGenerated(this.presenter.getDateToday());
        this.presenter.onLoadTicketsToday(this.presenter.getDateToday());
        this.presenter.onLoadSpentMoney(this.presenter.getDateToday());
    }

    public void tableStyles() {
        modelo.addColumn("#Ticket");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Total");
        tlbMoneyGenerated.setModel(modelo);
        TableColumn columnT = tlbMoneyGenerated.getColumn("#Ticket");
        columnT.setResizable(false);
        columnT.setPreferredWidth(10);
        TableColumn columnaF = tlbMoneyGenerated.getColumn("Fecha");
        columnaF.setResizable(false);
        columnaF.setPreferredWidth(20);
        TableColumn columnaM = tlbMoneyGenerated.getColumn("Hora");
        columnaM.setPreferredWidth(25);
        columnaM.setResizable(false);
        TableColumn columnaTo = tlbMoneyGenerated.getColumn("Total");
        columnaTo.setResizable(false);
        columnaTo.setPreferredWidth(20);
        tlbMoneyGenerated.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        tlbMoneyGenerated.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.jScrollPane2.getViewport().setBackground(new Color(255, 255, 255));
        this.jScrollPane2.getVerticalScrollBar().setUI(new MyScrollbarUI());
        this.jScrollPane2.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        
            
        modeloSpent.addColumn("Producto");
        modeloSpent.addColumn("Cantidad");
        modeloSpent.addColumn("Gastado");
        modeloSpent.addColumn("Fecha");
        tlbMoneySpend.setModel(modeloSpent);
        TableColumn columnP = tlbMoneySpend.getColumn("Producto");
        columnP.setResizable(false);
        columnP.setPreferredWidth(10);
        TableColumn columnaC = tlbMoneySpend.getColumn("Cantidad");
        columnaC.setResizable(false);
        columnaC.setPreferredWidth(20);
        TableColumn columnaG = tlbMoneySpend.getColumn("Gastado");
        columnaG.setPreferredWidth(25);
        columnaG.setResizable(false);
        TableColumn columnaFE = tlbMoneySpend.getColumn("Fecha");
        columnaFE.setResizable(false);
        columnaFE.setPreferredWidth(20);
        tlbMoneySpend.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        tlbMoneySpend.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        
        this.jScrollPane1.getViewport().setBackground(new Color(255, 255, 255));
        this.jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        this.jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbMoneySpend = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbMoneyGenerated = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        moneyGenerated = new javax.swing.JLabel();
        spentMoney = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnShowCashCourt = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tlbMoneySpend.setBackground(new java.awt.Color(0, 0, 0));
        tlbMoneySpend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tlbMoneySpend.setForeground(new java.awt.Color(255, 255, 255));
        tlbMoneySpend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tlbMoneySpend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tlbMoneySpend.setDoubleBuffered(true);
        tlbMoneySpend.setRowHeight(20);
        tlbMoneySpend.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tlbMoneySpend.getTableHeader().setReorderingAllowed(false);
        tlbMoneySpend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbMoneySpendMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbMoneySpend);

        jLabel17.setBackground(new java.awt.Color(58, 159, 171));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(58, 159, 171));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("SALIDAS");

        tlbMoneyGenerated.setBackground(new java.awt.Color(0, 0, 0));
        tlbMoneyGenerated.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tlbMoneyGenerated.setForeground(new java.awt.Color(255, 255, 255));
        tlbMoneyGenerated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tlbMoneyGenerated.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tlbMoneyGenerated.setDoubleBuffered(true);
        tlbMoneyGenerated.setRowHeight(20);
        tlbMoneyGenerated.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tlbMoneyGenerated.getTableHeader().setReorderingAllowed(false);
        tlbMoneyGenerated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbMoneyGeneratedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tlbMoneyGenerated);

        jLabel18.setBackground(new java.awt.Color(58, 159, 171));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(58, 159, 171));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Total salidas:");

        jLabel19.setBackground(new java.awt.Color(58, 159, 171));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(58, 159, 171));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("ENTRADAS");

        jLabel20.setBackground(new java.awt.Color(58, 159, 171));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(58, 159, 171));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Total entradas:");

        moneyGenerated.setBackground(new java.awt.Color(58, 159, 171));
        moneyGenerated.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        moneyGenerated.setForeground(new java.awt.Color(58, 159, 171));
        moneyGenerated.setText("$0.00");

        spentMoney.setBackground(new java.awt.Color(58, 159, 171));
        spentMoney.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        spentMoney.setForeground(new java.awt.Color(58, 159, 171));
        spentMoney.setText("$0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyGenerated, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spentMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spentMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(58, 159, 171));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(58, 159, 171));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas/caja.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CORTE CAJA");

        btnShowCashCourt.setBackground(new java.awt.Color(255, 255, 255));
        btnShowCashCourt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnShowCashCourt.setForeground(new java.awt.Color(58, 159, 171));
        btnShowCashCourt.setText("CORTE CAJA");
        btnShowCashCourt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowCashCourt.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnShowCashCourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCashCourtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowCashCourt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowCashCourt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void btnShowCashCourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCashCourtActionPerformed
        info.setVisible(true);
    }//GEN-LAST:event_btnShowCashCourtActionPerformed

    private void tlbMoneyGeneratedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbMoneyGeneratedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tlbMoneyGeneratedMouseClicked

    private void tlbMoneySpendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbMoneySpendMouseClicked

    }//GEN-LAST:event_tlbMoneySpendMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnShowCashCourt;
    private principal.MaterialButton cerrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel moneyGenerated;
    private javax.swing.JLabel spentMoney;
    public static javax.swing.JTable tlbMoneyGenerated;
    public static javax.swing.JTable tlbMoneySpend;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cleanTable() {
        int filas = modelo.getRowCount();
        for (int i = 0; filas > i; i++) {
            modelo.removeRow(0);
        }
    }
    
    @Override
    public void cleanTableSpend() {
        int filas = modeloSpent.getRowCount();
        for (int i = 0; filas > i; i++) {
            modeloSpent.removeRow(0);
        }
    }

    @Override
    public void onError(ExceptionPvLite exceptionPvLite) {
        ErrorAlert errorAlert = new ErrorAlert(desktop, true);
        errorAlert.titulo.setText("Error");
        errorAlert.msj.setText(exceptionPvLite.getMessage());
        errorAlert.msj1.setText("<html>" + exceptionPvLite.getCauseMessage() + "</html>");
        errorAlert.setVisible(true);
    }

    
    @Override
    public void onShowTicketsToday(List<Court> court) {
        Object[] data = new Object[4];
        court.forEach((cour) -> {
            data[0] = cour.getIdTicket();
            data[1] = cour.getDate();
            data[2] = cour.getHour();
            data[3] = cour.getAmount();
            modelo.addRow(data);
        });
    }

    @Override
    public void onShowResumeMoney(String moneyGenerated, String expenseMoney, String initialBalance, String total) {
        this.moneyGenerated.setText(moneyGenerated);
        this.spentMoney.setText(expenseMoney);
        this.info = new DetailsCashCourt(desktop, true,moneyGenerated,expenseMoney, initialBalance,total);
    }

    @Override
    public void onShowSpentMoney(List<Spents> spent) {
        /*Object[] data = new Object[4];
        spent.forEach((spen) -> {
            data[0] = spen.getDescription();
            data[1] = spen.getQuantite();
            data[2] = spen.getSpent();
            data[3] = spen.getDate();
            modeloSpent.addRow(data);
        });*/
    }

}
